### ISSUE TITLE
Build job marked as failed if no changes.

### ISSUE THREAD

**Issue by qmacro** [qmacro/qmacro#10]
The `build.yml` workflow has a single job, 'build'. This job has a step that is designed to emit a high return code if there are no changes:

```yaml
      - name: Check for changes (fail if none)
        run: |
          ! git diff --quiet
```

This is then checked in the 'commit changes' step, so that no commit is done if it's not needed:

```yaml
      - name: Commit changes if required
        if: ${{ success() }}
```

While the use of `continue-on-error` at the job level means that the job runs to completion and the workflow itself is marked as complete, the job is shown to have failed, which is not ideal:

<img width="1009" alt="Screen Shot 2021-01-04 at 13 08 48" src="https://user-images.githubusercontent.com/73068/103538456-22236680-4e8e-11eb-99ed-26856e47df03.png">
